name: "Tests"

on:
  - "pull_request"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
        rails-version:
          - "6.1"
          - "7.0"
          - "main"

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    name: ${{ format('Tests (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "ruby/setup-ruby@v1"
        with:
          rubygems: 3.3.13
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Build Styles with tailwindcss-rails
        run: bin/rails runner 'require "tailwindcss-rails"; `bin/tailwindcss`'

      - name: Execute Test Suite
        run: bin/rails test test/**/*_test.rb

      - name: Fail when generated changes are not checked-in
        run: git update-index --refresh && git diff-index --quiet HEAD --
