name: "Tests"

on:
  - "pull_request"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rails-version:
          - "7.0"
          - "6.1"
          - "main"
        ruby-version:
          - "3.2"
          - "2.7"

    env:
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails-version }}

    name: ${{ format('Tests rails@{0} ruby@{1}', matrix.rails-version, matrix.ruby-version) }}
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "ruby/setup-ruby@v1"
        with:
          rubygems: latest
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Build Styles with tailwindcss-rails
        run: bin/rails runner 'require "tailwindcss-rails"; `bin/tailwindcss`'

      - name: Build Highlight Styles with rouge
        run: bin/rails runner 'require "rouge"; `bin/highlights`; end'

      - name: Run tests with Rouge
        run: bin/rails test test/

      - name: Run tests without Rouge
        run: ROUGE_ENABLED=false bin/rails test test/

      - name: Fail when generated changes are not checked-in
        run: git update-index --refresh && git diff-index --quiet HEAD --
